-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "colors" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sizes" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0;
